# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: mattrayner/lamp:latest-1804
        environment:
          # ss config
          - SS_DATABASE_CLASS=MySQLDatabase
          - SS_DATABASE_SERVER=127.0.0.1
          - SS_DATABASE_USERNAME=root
          - SS_DATABASE_PASSWORD=ubuntu
          - SS_DATABASE_NAME=circle_test
          - SS_ENVIRONMENT_TYPE=dev
          # jwt prefix
          - JWT_PREFIX=jwt_
          - JWT_SIGNER_KEY=test_signer
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: ~/var/www

    steps:
      - run: apt-get update && apt-get -y upgrade && apt-get -y install php-intl && apt-get -y autoremove
      - run: composer self-update
      - run: composer create-project firesphere/graphql-jwt:dev-master ~/var/www -n
      - run: vendor/bin/sake dev/build

      # run tests!
      - run: vendor/bin/phpunit --coverage-clover=coverage.xml -d memory_limit=512M tests/unit
      - run: bash <(curl -s https://codecov.io/bash) -f coverage.xml

